# Generated by Django 6.0.5 on 2026-05-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='departments',
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('departments', models.ManyToManyField(blank=True, to='employees.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_groups',
            field=models.ManyToManyField(blank=True, to='employees.employeegroup'),
        ),
    ]
