# Generated by Django 6.0.5 on 2026-05-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_userprofile_departments_employeegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, choices=[('trung_hoc', 'Trung học'), ('trung_cap', 'Trung cấp'), ('cao_dang', 'Cao đẳng'), ('dai_hoc', 'Đại học'), ('thac_si', 'Thạc sĩ'), ('tien_si', 'Tiến sĩ')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_card',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('doc_than', 'Độc thân'), ('da_ket_hon', 'Đã kết hôn'), ('ly_hon', 'Ly hôn'), ('goa', 'Góa')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
