# Generated by Django 6.0.5 on 2026-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
