# Generated by Django 6.0.5 on 2026-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
