# Generated by Django 6.0.5 on 2026-05-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_userprofile_can_add_userprofile_can_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_add',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='employee_groups',
        ),
        migrations.CreateModel(
            name='UserGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_perms', to='employees.employeegroup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_perms', to='employees.userprofile')),
            ],
            options={
                'ordering': ['group__name'],
                'unique_together': {('profile', 'group')},
            },
        ),
    ]
