# Generated by Django 6.0.5 on 2026-05-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_userprofile_can_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
