# Generated by Django 6.0.5 on 2026-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_userprofile_feature_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app_contracts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app_payroll',
            field=models.BooleanField(default=False),
        ),
    ]
