# Generated by Django 6.0.5 on 2026-05-16 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_userprofile_app_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('app_employees', models.BooleanField(default=False)),
                ('app_contracts', models.BooleanField(default=False)),
                ('app_attendance', models.BooleanField(default=False)),
                ('app_payroll', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_import', models.BooleanField(default=False)),
                ('can_view_dashboard', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, related_name='staff_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffGroupDeptPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('emp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_perms', to='employees.employeegroup')),
                ('staff_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_perms', to='employees.staffgroup')),
            ],
            options={
                'ordering': ['emp_group__name'],
                'unique_together': {('staff_group', 'emp_group')},
            },
        ),
    ]
