# Generated by Django 6.0.5 on 2026-05-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_staffgroup_and_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('dang_lam', 'Đang làm việc'), ('thu_viec', 'Thử việc'), ('nghi_viec', 'Nghỉ việc')], default='dang_lam', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
    ]
