# Generated by Django 6.0.5 on 2026-05-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_status_termination'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('dang_lam', 'Đang làm việc'), ('thu_viec', 'Thử việc'), ('nghi_phep', 'Nghỉ phép'), ('nghi_sinh', 'Nghỉ thai sản'), ('nghi_khong_luong', 'Nghỉ không lương'), ('nghi_om', 'Nghỉ ốm dài ngày'), ('nghi_viec', 'Nghỉ việc')], default='dang_lam', max_length=20),
        ),
    ]
