# Generated by Django 6.0.5 on 2026-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_add_status_choices_and_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
