# Generated by Django 6.0.5 on 2026-05-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='scheduled_termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
