# Generated by Django 6.0.5 on 2026-05-18 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_add_status_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('edit', 'Chỉnh sửa'), ('delete', 'Xóa'), ('status_change', 'Đổi trạng thái'), ('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('import', 'Import dữ liệu'), ('export', 'Xuất file')], max_length=20)),
                ('target_type', models.CharField(choices=[('employee', 'Nhân viên'), ('department', 'Phòng ban'), ('emp_group', 'Nhóm bộ phận'), ('staff_group', 'Nhóm người dùng'), ('user', 'Tài khoản'), ('permission', 'Phân quyền'), ('system', 'Hệ thống')], max_length=20)),
                ('target_name', models.CharField(blank=True, max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
