# Generated by Django 5.2 on 2026-05-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(choices=[('employee', 'Nhân viên'), ('department', 'Phòng ban'), ('emp_group', 'Nhóm bộ phận'), ('staff_group', 'Nhóm người dùng'), ('user', 'Tài khoản'), ('permission', 'Phân quyền'), ('contract', 'Hợp đồng'), ('system', 'Hệ thống')], max_length=20),
        ),
    ]
