# Generated by Django 5.2 on 2026-05-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_add_contract_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffgroup',
            name='app_talent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app_talent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(choices=[('employee', 'Nhân viên'), ('department', 'Phòng ban'), ('emp_group', 'Nhóm bộ phận'), ('staff_group', 'Nhóm người dùng'), ('user', 'Tài khoản'), ('permission', 'Phân quyền'), ('contract', 'Hợp đồng'), ('talent', 'Tuyển dụng & Đào tạo'), ('system', 'Hệ thống')], max_length=20),
        ),
    ]
