# Generated by Django 5.2 on 2026-05-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_staffgroup_app_talent_userprofile_app_talent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(choices=[('employee', 'Nhân viên'), ('department', 'Phòng ban'), ('emp_group', 'Nhóm bộ phận'), ('staff_group', 'Nhóm người dùng'), ('user', 'Tài khoản'), ('permission', 'Phân quyền'), ('contract', 'Hợp đồng'), ('talent', 'Tuyển dụng & Đào tạo'), ('attendance', 'Chấm công'), ('leave', 'Nghỉ phép'), ('system', 'Hệ thống')], max_length=20),
        ),
    ]
