# Generated by Django 5.2 on 2026-05-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_add_user_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffgroup',
            name='can_approve_talent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_talent',
            field=models.BooleanField(default=False),
        ),
    ]
