# Generated by Django 5.2 on 2026-05-20 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('type', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('danger', 'Nguy hiểm'), ('success', 'Thành công')], default='info', max_length=20, verbose_name='Loại')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
