# Generated by Django 5.2 on 2026-05-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0021_add_contract_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Số hợp đồng')),
                ('contract_type', models.CharField(choices=[('thu_viec', 'Thử việc'), ('xd_1_nam', 'HĐLĐ xác định thời hạn 1 năm'), ('xd_3_nam', 'HĐLĐ xác định thời hạn 3 năm'), ('khong_xd', 'HĐLĐ không xác định thời hạn'), ('thuc_tap', 'Hợp đồng thực tập')], max_length=20, verbose_name='Loại hợp đồng')),
                ('status', models.CharField(choices=[('hieu_luc', 'Còn hiệu lực'), ('sap_het_han', 'Sắp hết hạn'), ('het_han', 'Hết hạn'), ('gia_han', 'Đã gia hạn'), ('cham_dut', 'Đã chấm dứt')], default='hieu_luc', max_length=20, verbose_name='Trạng thái')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Lương theo HĐ')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Ngày chấm dứt')),
                ('termination_reason', models.CharField(blank=True, choices=[('het_hop_dong', 'Hết hạn hợp đồng'), ('tu_nghi', 'Nhân viên tự nghỉ'), ('sa_thai', 'Sa thải'), ('thoa_thuan', 'Thỏa thuận hai bên'), ('khac', 'Khác')], max_length=20, verbose_name='Lý do chấm dứt')),
                ('termination_note', models.TextField(blank=True, verbose_name='Ghi chú chấm dứt')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.department', verbose_name='Phòng ban')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employee', verbose_name='Nhân viên')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='contracts.contract', verbose_name='Gia hạn từ HĐ')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Hợp đồng',
                'ordering': ['-created_at'],
            },
        ),
    ]
