# Generated by Django 5.2 on 2026-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notice_period_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Thời hạn báo trước (ngày)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày ký hợp đồng'),
        ),
    ]
