# Generated by Django 5.2 on 2026-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_add_signed_date_notice_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/files/', verbose_name='File hợp đồng'),
        ),
    ]
