# Generated by Django 5.2 on 2026-05-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_dept_fk_to_departments_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='allowances',
            field=models.JSONField(blank=True, default=dict, help_text='VD: {"housing": 2000000, "transport": 500000}', verbose_name='Phụ cấp'),
        ),
        migrations.AddField(
            model_name='contract',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Lương cơ bản'),
        ),
    ]
