# Generated by Django 5.2 on 2026-05-19 03:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0022_staffgroup_app_talent_userprofile_app_talent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('topcv', 'TopCV'), ('vietnamworks', 'VietnamWorks'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('website', 'Website công ty'), ('referral', 'Giới thiệu nội bộ'), ('direct', 'Nộp trực tiếp'), ('other', 'Khác')], default='other', max_length=20)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='recruitment/cv/')),
                ('cover_letter', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('new', 'Mới nộp'), ('screening', 'Sàng lọc'), ('interview', 'Phỏng vấn'), ('offer', 'Đề nghị'), ('hired', 'Đã tuyển'), ('rejected', 'Loại')], default='new', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('converted_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants_created', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='employees.employee')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('interview_type', models.CharField(choices=[('phone', 'Điện thoại'), ('online', 'Online'), ('in_person', 'Trực tiếp'), ('technical', 'Chuyên môn')], default='in_person', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('no_show', 'Vắng mặt')], default='scheduled', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='talent.applicant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_created', to=settings.AUTH_USER_MODEL)),
                ('interviewers', models.ManyToManyField(blank=True, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_salary', models.DecimalField(decimal_places=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('probation_months', models.PositiveIntegerField(default=2)),
                ('benefits_note', models.TextField(blank=True)),
                ('offer_letter_file', models.FileField(blank=True, null=True, upload_to='recruitment/offers/')),
                ('deadline_response', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('sent', 'Đã gửi'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Từ chối'), ('expired', 'Hết hạn')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joboffer', to='talent.applicant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headcount', models.PositiveIntegerField(default=1)),
                ('employment_type', models.CharField(choices=[('full_time', 'Toàn thời gian'), ('part_time', 'Bán thời gian'), ('internship', 'Thực tập'), ('seasonal', 'Thời vụ')], default='full_time', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('location', models.CharField(default='Văn phòng chính', max_length=200)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('open', 'Đang tuyển'), ('interviewing', 'Đang PV'), ('filled', 'Đã tuyển đủ'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('source_channels', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='employees.department')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='talent.jobposition'),
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('soft_skill', 'Kỹ năng mềm'), ('technical', 'Chuyên môn'), ('safety', 'An toàn lao động'), ('compliance', 'Tuân thủ quy định'), ('onboarding', 'Hội nhập')], default='technical', max_length=20)),
                ('delivery_method', models.CharField(choices=[('classroom', 'Tập trung tại lớp'), ('online', 'Trực tuyến'), ('on_job', 'Thực chiến tại chỗ'), ('blended', 'Kết hợp')], default='classroom', max_length=20)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('provider', models.CharField(default='Nội bộ', max_length=200)),
                ('cost_per_person', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('certificate_validity_months', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('target_departments', models.ManyToManyField(blank=True, related_name='training_courses', to='employees.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'Đã đăng ký'), ('attended', 'Đã tham dự'), ('absent', 'Vắng mặt'), ('cancelled', 'Đã hủy')], default='registered', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('result', models.CharField(choices=[('pending', 'Chưa có kết quả'), ('pass', 'Đạt'), ('fail', 'Không đạt')], default='pending', max_length=20)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_comment', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='employees.employee')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='employees.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='talent.trainingcourse')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='talent.trainingenrollment')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('trainer_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Đã lên kế hoạch'), ('ongoing', 'Đang diễn ra'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='talent.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL)),
                ('trainer_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='talent.trainingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('job_position', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingenrollment',
            unique_together={('session', 'employee')},
        ),
    ]
