# Generated by Django 5.2 on 2026-05-28 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_tables'),
        ('employees', '0025_add_user_to_employee'),
        ('talent', '0002_dept_fk_to_departments_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('new', 'Mới nộp'), ('screening', 'Sàng lọc'), ('interview', 'Phỏng vấn'), ('offer', 'Đề nghị'), ('hired', 'Đã tuyển'), ('rejected', 'Loại')], max_length=20)),
                ('to_stage', models.CharField(choices=[('new', 'Mới nộp'), ('screening', 'Sàng lọc'), ('interview', 'Phỏng vấn'), ('offer', 'Đề nghị'), ('hired', 'Đã tuyển'), ('rejected', 'Loại')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Năm kế hoạch, ví dụ 2026')),
                ('deadline', models.DateField(blank=True, help_text='Hạn hoàn thành', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('in_progress', 'Đang học'), ('completed', 'Hoàn thành'), ('overdue', 'Quá hạn')], default='not_started', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['year', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='TrainingNeedAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name_free', models.CharField(blank=True, help_text='Tên khóa học nếu chưa có trong danh mục', max_length=200)),
                ('reason', models.TextField(help_text='Lý do cần đào tạo, kỹ năng cần nâng cao')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('enrolled', 'Đã đăng ký học')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='hired_at',
            field=models.DateTimeField(blank=True, help_text='Tự động set khi stage chuyển sang hired', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Link Zoom/Google Meet/Teams'),
        ),
        migrations.AddField(
            model_name='interview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('strong_yes', 'Rất đồng ý tuyển'), ('yes', 'Đồng ý tuyển'), ('maybe', 'Cân nhắc'), ('no', 'Không đồng ý')], max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='score_communication',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='interview',
            name='score_culture_fit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='interview',
            name='score_technical',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='Học viên đạt được gì sau khóa học (mỗi dòng 1 mục tiêu)'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='passing_score',
            field=models.PositiveIntegerField(default=60, help_text='Điểm tối thiểu để đạt (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Yêu cầu trước khi tham gia'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='materials_file',
            field=models.FileField(blank=True, help_text='Tài liệu đào tạo (PDF, PPT...)', null=True, upload_to='training/materials/'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='online_meeting_url',
            field=models.URLField(blank=True, help_text='Link Zoom/Meet/Teams nếu học online'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Link video ghi lại buổi học'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['stage'], name='talent_applicant_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['applied_at'], name='talent_app_applied_at_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['stage', 'applied_at'], name='talent_app_stage_date_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['status'], name='talent_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['status', 'created_at'], name='talent_job_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcertificate',
            index=models.Index(fields=['expiry_date', 'is_active'], name='talent_cert_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['result'], name='talent_enrollment_result_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['status'], name='talent_enrollment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['status', 'start_date'], name='talent_session_status_date_idx'),
        ),
        migrations.AddField(
            model_name='applicantstagehistory',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='talent.applicant'),
        ),
        migrations.AddField(
            model_name='applicantstagehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetrainingplan',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetrainingplan',
            name='completed_enrollment',
            field=models.ForeignKey(blank=True, help_text='Enrollment hoàn thành kế hoạch này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfills_plans', to='talent.trainingenrollment'),
        ),
        migrations.AddField(
            model_name='employeetrainingplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='talent.trainingcourse'),
        ),
        migrations.AddField(
            model_name='employeetrainingplan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Khóa học nếu đã có trong danh mục', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='needs', to='talent.trainingcourse'),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingneedassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='employeetrainingplan',
            unique_together={('employee', 'course', 'year')},
        ),
    ]
