# Generated by Django 5.2 on 2026-05-28 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_applicantstagehistory_employeetrainingplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetrainingplan',
            name='approval_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú duyệt'),
        ),
        migrations.AddField(
            model_name='employeetrainingplan',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='employeetrainingplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetrainingplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetrainingplan',
            name='is_employee_request',
            field=models.BooleanField(default=False, verbose_name='Nhân viên tự đề xuất'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='approval_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú duyệt'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
