# Generated by Django 5.2 on 2026-05-20 03:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0005_contract_allowances_contract_basic_salary'),
        ('employees', '0025_add_user_to_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhxh_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Tỷ lệ BHXH NV đóng (%)')),
                ('bhyt_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, verbose_name='Tỷ lệ BHYT NV đóng (%)')),
                ('bhtn_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Tỷ lệ BHTN NV đóng (%)')),
                ('personal_deduction', models.DecimalField(decimal_places=0, default=Decimal('11000000'), max_digits=15, verbose_name='Giảm trừ bản thân (đ/tháng)')),
                ('dependent_deduction', models.DecimalField(decimal_places=0, default=Decimal('4400000'), max_digits=15, verbose_name='Giảm trừ mỗi người phụ thuộc (đ/tháng)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình bảng lương',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Năm')),
                ('basic_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Lương cơ bản')),
                ('allowances_detail', models.JSONField(blank=True, default=dict, verbose_name='Chi tiết phụ cấp')),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Tổng giờ OT')),
                ('ot_pay', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tiền OT')),
                ('other_additions', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thưởng / Phụ cấp khác')),
                ('gross_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng thu nhập (Gross)')),
                ('bhxh_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='BHXH (8%)')),
                ('bhyt_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='BHYT (1.5%)')),
                ('bhtn_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='BHTN (1%)')),
                ('total_insurance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng bảo hiểm')),
                ('dependents', models.PositiveSmallIntegerField(default=0, verbose_name='Số người phụ thuộc')),
                ('taxable_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thu nhập chịu thuế')),
                ('pit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thuế TNCN')),
                ('other_deductions', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Khấu trừ khác')),
                ('net_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Lương thực nhận (Net)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm tính')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='contracts.contract', verbose_name='Hợp đồng')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Phiếu lương',
                'ordering': ['-year', '-month', 'employee__employee_code'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
