# Generated by Django 5.2 on 2026-05-20 04:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_allowances_contract_basic_salary'),
        ('employees', '0025_add_user_to_employee'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Năm')),
                ('si_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='BHXH NV (%)')),
                ('hi_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, verbose_name='BHYT NV (%)')),
                ('ui_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='BHTN NV (%)')),
                ('si_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('17.50'), max_digits=5, verbose_name='BHXH Chủ (%)')),
                ('hi_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='BHYT Chủ (%)')),
                ('ui_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='BHTN Chủ (%)')),
                ('salary_cap', models.DecimalField(decimal_places=0, default=Decimal('46800000'), max_digits=15, verbose_name='Mức trần đóng BH (đ/tháng)')),
                ('personal_deduction', models.DecimalField(decimal_places=0, default=Decimal('15500000'), max_digits=15, verbose_name='Giảm trừ bản thân (đ/tháng)')),
                ('dependent_deduction', models.DecimalField(decimal_places=0, default=Decimal('6200000'), max_digits=15, verbose_name='Giảm trừ người phụ thuộc (đ/người/tháng)')),
            ],
            options={
                'verbose_name': 'Cấu hình bảo hiểm theo năm',
                'ordering': ['-year'],
            },
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bhtn_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='BHTN'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bhxh_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='BHXH'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bhyt_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='BHYT'),
        ),
        migrations.CreateModel(
            name='OTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày tăng ca')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Số giờ OT')),
                ('ot_type', models.CharField(choices=[('normal', 'Bình thường (1.5×)'), ('night', 'Ban đêm (2.0×)'), ('weekend', 'Cuối tuần (2.0×)'), ('holiday', 'Ngày lễ (3.0×)')], default='normal', max_length=20, verbose_name='Loại OT')),
                ('multiplier', models.DecimalField(decimal_places=1, default=Decimal('1.5'), max_digits=3, verbose_name='Hệ số lương')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do tăng ca')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm duyệt')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ot_records', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_records', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bản ghi tăng ca',
                'ordering': ['-date', 'employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('earning', 'Thu nhập'), ('deduction', 'Khấu trừ'), ('tax', 'Thuế')], max_length=20, verbose_name='Loại')),
                ('name', models.CharField(max_length=200, verbose_name='Mô tả')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip', verbose_name='Phiếu lương')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PITBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Thứ tự bậc')),
                ('min_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thu nhập từ (đ/tháng)')),
                ('max_income', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Thu nhập đến (đ/tháng, để trống = không giới hạn)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Thuế suất (VD: 0.05 = 5%)')),
            ],
            options={
                'verbose_name': 'Bậc thuế TNCN',
                'ordering': ['year', 'order'],
                'unique_together': {('year', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Hiệu lực từ ngày')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Hiệu lực đến ngày')),
                ('basic_salary', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Lương cơ bản (đ/tháng)')),
                ('allowances', models.JSONField(blank=True, default=dict, help_text='VD: {"Phụ cấp nhà ở": 2000000, "Phụ cấp xăng xe": 500000}', verbose_name='Phụ cấp chi tiết')),
                ('dependents', models.IntegerField(default=0, verbose_name='Số người phụ thuộc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_configs', to='contracts.contract', verbose_name='Hợp đồng liên kết')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_configs', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Cấu hình lương NV',
                'ordering': ['-effective_from'],
            },
        ),
    ]
