# Generated by Django 5.2 on 2026-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_contracts_active', models.BooleanField(default=False)),
                ('app_attendance_active', models.BooleanField(default=False)),
                ('app_payroll_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trạng thái ứng dụng',
            },
        ),
    ]
