# Generated by Django 5.2 on 2026-05-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstatus',
            name='app_talent_active',
            field=models.BooleanField(default=False),
        ),
    ]
