# Generated by Django 5.2 on 2026-05-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0023_alter_activitylog_target_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chính sách')),
                ('base_annual_days', models.IntegerField(default=12, verbose_name='Số ngày cơ bản/năm')),
                ('increment_years', models.IntegerField(default=5, verbose_name='Cứ mỗi X năm thâm niên')),
                ('increment_days', models.IntegerField(default=1, verbose_name='Cộng thêm X ngày')),
                ('is_default', models.BooleanField(default=False, verbose_name='Chính sách mặc định')),
            ],
            options={
                'verbose_name': 'Chính sách phép năm',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại nghỉ')),
                ('code', models.CharField(default='other', max_length=20, verbose_name='Mã loại')),
                ('max_days_per_year', models.IntegerField(default=0, help_text='0 = không giới hạn', verbose_name='Số ngày tối đa/năm')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Hưởng lương')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Cần duyệt')),
                ('allow_half_day', models.BooleanField(default=True, verbose_name='Cho nghỉ nửa ngày')),
                ('document_required', models.BooleanField(default=False, verbose_name='Cần giấy tờ')),
                ('carry_over', models.BooleanField(default=False, verbose_name='Chuyển năm sau')),
                ('gender_restriction', models.CharField(choices=[('all', 'Tất cả'), ('female', 'Nữ'), ('male', 'Nam')], default='all', max_length=10, verbose_name='Giới tính áp dụng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Loại nghỉ phép',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên ngày lễ')),
                ('date', models.DateField(unique=True, verbose_name='Ngày')),
                ('year', models.IntegerField(editable=False, verbose_name='Năm')),
            ],
            options={
                'verbose_name': 'Ngày lễ',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ca')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('break_minutes', models.IntegerField(default=60, verbose_name='Phút nghỉ giữa ca')),
                ('standard_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Giờ chuẩn/ngày')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Số ngày nghỉ')),
                ('half_day', models.BooleanField(default=False, verbose_name='Nghỉ nửa ngày')),
                ('half_day_period', models.CharField(blank=True, choices=[('morning', 'Buổi sáng'), ('afternoon', 'Buổi chiều')], max_length=20, verbose_name='Buổi nghỉ')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('document', models.FileField(blank=True, null=True, upload_to='leaves/documents/', verbose_name='Giấy tờ đính kèm')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt cấp 1'), ('waiting_hr', 'Chờ HR duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Nhân viên')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.leavetype', verbose_name='Loại nghỉ')),
            ],
            options={
                'verbose_name': 'Đơn xin nghỉ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Cấp duyệt')),
                ('action', models.CharField(choices=[('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('forwarded', 'Chuyển tiếp')], max_length=20, verbose_name='Hành động')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('acted_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm duyệt')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='attendance.leaverequest', verbose_name='Đơn xin nghỉ')),
            ],
            options={
                'verbose_name': 'Lịch sử duyệt đơn',
                'ordering': ['acted_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('allocated_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Ngày được cấp')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Đã dùng')),
                ('pending_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Đang chờ duyệt')),
                ('carried_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Chuyển từ năm trước')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='Nhân viên')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.leavetype', verbose_name='Loại nghỉ')),
            ],
            options={
                'verbose_name': 'Số dư ngày phép',
                'ordering': ['-year', 'employee__employee_code'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giờ làm thực tế')),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giờ OT')),
                ('status', models.CharField(choices=[('present', 'Đi làm'), ('absent', 'Vắng không phép'), ('half_day', 'Nửa ngày'), ('late', 'Đi muộn/về sớm'), ('on_leave', 'Nghỉ phép'), ('holiday', 'Nghỉ lễ')], default='present', max_length=20, verbose_name='Trạng thái')),
                ('source', models.CharField(choices=[('manual', 'Nhập tay'), ('import_file', 'Import file'), ('system', 'Hệ thống')], default='manual', max_length=20, verbose_name='Nguồn')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Nhân viên')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift', verbose_name='Ca làm việc')),
            ],
            options={
                'verbose_name': 'Bản ghi chấm công',
                'ordering': ['-date', 'employee__employee_code'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
