# Generated by Django 5.2 on 2026-05-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='ot_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Hệ số OT'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='ot_type',
            field=models.CharField(blank=True, choices=[('normal', 'Bình thường (1.5x)'), ('night', 'Ban đêm (2.0x)'), ('weekend', 'Cuối tuần (2.0x)'), ('holiday', 'Ngày lễ (3.0x)')], max_length=20, null=True, verbose_name='Loại OT'),
        ),
    ]
